[screen]
split = "horizontal"

[[screen.children]]
size = 25
split = "vertical"

[[screen.children.children]]
command = "alacritty --title medium-window"
size = 60

[[screen.children.children]]
command = "alacritty --title tiny-window"
size = 40

[[screen.children]]
command = "alacritty --title middle-panel"
size = 50

[[screen.children]]
command = "alacritty --title right-panel"
size = 25
